# In this directory, run the following command to build this builder. sddssdds
# $ gcloud builds submit . --config=cloudbuild.yaml --substitutions _BUCKET='<bucket name>'
steps:
- name: 'gcr.io/cloud-init-248919/terraform'
  args: ['init',
  # '-backend-config=project=cloud-init-248919',
    '-backend-config=bucket=${_BUCKET}']
  env:
    - "TF_VAR_project-name=cloud-init-248919"
- name: 'gcr.io/cloud-init-248919/terraform'
  args: ['plan']
  env:
    - "TF_VAR_project-name=cloud-init-248919"
- name: 'gcr.io/cloud-init-248919/terraform'
  args: ['apply', '-auto-approve']
  env:
    - "TF_VAR_project-name=cloud-init-248919"
- name: 'gcr.io/cloud-init-248919/terraform'
  args: ['destroy', '-auto-approve']
  env:
    - "TF_VAR_project-name=cloud-init-248919"
substitutions:
    _BUCKET: adfgdsfgdafgfdsg
tags: ['cloud-builders-community']
